# 基本 github.com のレポジトリーを指定するだけ
[[plugins]] #プラグインマネージャー
repo = 'Shougo/dein.vim'

[[plugins]] #vimで非同期処理ができるようになる
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]] #統合ユーザインターフェース
repo = 'Shougo/unite.vim'

[[plugins]] #vimからshellを起動
repo = 'Shougo/vimshell.vim'

[[plugins]] #the_silver_searcher(grepより早いgrep検索)
repo = 'rking/ag.vim'

[[plugins]] #ディレクトリをツリー表示
repo = 'scrooloose/nerdtree'

[[plugins]] #NEADTreeをタブ間で共有
repo = 'jistr/vim-nerdtree-tabs'

[[plugins]] #メソッド、変数、定数の一覧表示
repo = 'vim-scripts/taglist.vim'

[[plugins]] #gtags
repo = 'vim-scripts/gtags.vim'

[[plugins]] #Vimの中でGitを利用できる
repo = 'tpope/vim-fugitive'

[[plugins]] #左端にgitの差分を表示する
repo = 'airblade/vim-gitgutter'

[[plugins]] #vimのjkを早くする
repo = 'rhysd/accelerated-jk'

[[plugins]] #サブモードを定義
repo = 'kana/vim-submode'

[[plugins]] #インデントラインを表示
repo = 'Yggdroot/indentLine'

[[plugins]] #ステータスラインの強化
repo = 'itchyny/lightline.vim'

[[plugins]] #文章整形用プラグイン
repo = 'h1mesuke/vim-alignta'

[[plugins]] #help日本語化
repo = 'vim-jp/vimdoc-ja'

[[plugins]] #カラースキーマ
# colorscheme 設定は source 後に行う必要があるので VimEnter で行う。
# 但し Colorscheme イベントの発生が抑制されないよう nented を付ける。
repo = 'w0ng/vim-hybrid'
hook_add = '''
  set background=dark
  au MyAutoCmd VimEnter * nested colorscheme hybrid
'''

