[[plugins]] #プラグインマネージャー
repo = 'Shougo/dein.vim'

[[plugins]] #vimで非同期処理ができるようになる
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]] #ディレクトリをツリー表示
repo = 'scrooloose/nerdtree'

[[plugins]] #NEADTreeをタブ間で共有
repo = 'jistr/vim-nerdtree-tabs'

[[plugins]] #fzf path for homebrew
repo = '/usr/local/opt/fzf'

[[plugins]] #fzf
repo = 'junegunn/fzf.vim'

[[plugins]] #Vimの中でGitコマンドを利用
repo = 'tpope/vim-fugitive'

[[plugins]] #Gitの差分を表示
repo = 'airblade/vim-gitgutter'

[[plugins]] #global gtags
repo = 'vim-scripts/gtags.vim'

[[plugins]] #構文チェック
repo = 'vim-syntastic/syntastic'

[[plugins]] #ステータスラインの強化
repo = 'itchyny/lightline.vim'

[[plugins]] #インデントラインを表示
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]] #コメントアウト
repo = 'tpope/vim-commentary'

[[plugins]] #文章整形
repo = 'h1mesuke/vim-alignta'

[[plugins]] #vimのjkを高速化
repo = 'rhysd/accelerated-jk'

[[plugins]] #サブモードを定義
repo = 'kana/vim-submode'

[[plugins]] #xdebug
repo = 'joonty/vdebug'

[[plugins]] #smartyシンタックス
repo = 'vim-scripts/smarty-syntax'

#==================================
# ColorScheme
#==================================
[[plugins]]
#repo = 'w0ng/vim-hybrid'
repo = 'brendonrapp/smyck-vim'

# colorscheme 設定は source 後に行う必要があるので VimEnter で行う。
# 但し Colorscheme イベントの発生が抑制されないよう nented を付ける。
hook_add = '''
  set background=dark
  au MyAutoCmd VimEnter * nested colorscheme smyck
'''

